services:
  database:
    image: mongo
    container_name: mongo-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:${DB_PORT}

  api:
    build: .
    container_name: node-api
    depends_on:
      - database
    links:
      - database
    ports:
      - 4000:${API_PORT}

volumes:
  mongo-data:
